import time
import numpy as np
from src.environment.pettingzoo_env import HospitalEdgeEnv
from src.data.workload_generator import TaskStatus

def run_shn_demo():
    print("============================================================")
    print(" SHN + EDE DEMONSTRATION (Phase 8)")
    print("============================================================")
    env = HospitalEdgeEnv(max_steps=10, seed=42)
    env.reset(seed=42)
    
    er = env.edge_nodes["ER"]
    icu = env.edge_nodes["ICU"]
    radiology = env.edge_nodes["Radiology"]
    
    # Setup Tasks (clear the one generated by reset)
    er.task_queue.clear()
    er.local_execution_queue.clear()
    
    t1 = env.workload_gen.sample_task("ER", 0.0)
    t2 = env.workload_gen.sample_task("ER", 0.0)
    t1.required_gflops = 99999.0 # Make sure they take a while
    t1.remaining_compute_gflops = 99999.0
    t2.required_gflops = 99999.0
    t2.remaining_compute_gflops = 99999.0
    
    er.task_queue.append(t1)
    er.local_execution_queue.append(t2)
    
    # Fake ICU and Radiology PCAS states in ER's cache so ICU is chosen
    # ER is crashed, so it'll use its cache to recover.
    icu_msg = icu.anc.emit_broadcast(0.0, 0.1, 0.1, 2, 0.0, 20.0, pred_queue=2.0)
    rad_msg = radiology.anc.emit_broadcast(0.0, 0.9, 0.9, 9, 0.0, 50.0, pred_queue=9.0)
    
    er.receive_state_update(icu_msg)
    er.receive_state_update(rad_msg)
    
    print("\n[NORMAL] ER starts executing T2 (T1 waiting)")
    actions = {agent: env.action_dim - 1 for agent in env.agents}
    env.step(actions) # Takes 50ms step, T2 runs for 50ms
    
    print(f" -> T2 Status: {t2.status.name}")
    print(f" -> T2 Remaining Compute: {t2.remaining_compute_gflops:.2f} GFLOPS")
    
    print("\n[DISASTER] ER Node Crashes!")
    env.graph.crashed_nodes.add("ER")
    
    # Step again, environment detects crash, triggers handle_crash and recovery for t1
    # During this step's sim_time advance, the interrupt fires and orphans t2
    env.step(actions)
    
    # Step ONE MORE TIME so the environment can detect the newly orphaned t2 and recover it!
    env.step(actions)
    
    print(f"\n[RECOVERY] ER is_available: {er.is_available}")
    print(f" -> ER Tasks in Queue: {len(er.task_queue)}")
    print(f" -> ER Tasks in Execution: {len(er.local_execution_queue)}")
    print(f" -> T1 Status: {t1.status.name}")
    print(f" -> T2 Status: {t2.status.name}")
    print(f" -> T2 Remaining Compute Preserved: {t2.remaining_compute_gflops:.2f} GFLOPS (did not reset!)")
    
    # They should be recovered to ICU because ICU's pred_queue was 2.0 vs Radiology's 9.0
    # Generate explanation manually just to print it
    explanation = er.ede.generate_recovery_explanation(t1, "ICU", "because ER crashed")
    print(f"\n[EDE] Explanation generated during recovery:")
    print(explanation["report_text"] if explanation else "None")
    
    # Since they were transmitted with delay, they might not be in ICU yet. Run until time + 2000
    print("\n[NETWORK] Waiting for P2P transfer of orphaned tasks to destination...")
    env.sim_time_ms += 2000.0
    env.sim_env.run(until=env.sim_time_ms)
    
    print(f" -> ICU Queue Length: {len(icu.task_queue)}")
    all_icu_tasks = icu.task_queue + icu.local_execution_queue + icu.completed_tasks
    if t1 in all_icu_tasks and t2 in all_icu_tasks:
        print(" -> SUCCESS: Orphaned tasks successfully arrived at ICU private queue!")
    else:
        print(" -> ERROR: Tasks not found in ICU. They might be in transit or executed.")

    print("\n[RECOVERY METRICS]")
    print(env.recovery_metrics)

if __name__ == "__main__":
    run_shn_demo()
